name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2 via SSM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Deploy to EC2 instances
        run: |
          instance_ids=("${{ secrets.EC2_INSTANCE_ID_1 }}" "${{ secrets.EC2_INSTANCE_ID_2 }}")
          
          for instance_id in "${instance_ids[@]}"; do
            if [ -n "$instance_id" ]; then
              echo "Deploying to instance: $instance_id"

              # Create a temporary JSON file with proper escaping
              cat > /tmp/ssm-params.json << 'EOF'
          {
              "commands": [
                  "set -euo pipefail",
                  "cd /home/ec2-user/yubikirigennmann",
                  "git pull origin main",
                  "echo \"$DOT_ENV_PRODUCTION\" > .env",
                  "cat << 'DOCKER_COMPOSE_EOF' > docker-compose.prod.yml",
                  "services:",
                  "  api:",
                  "    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_API_REPOSITORY:latest",
                  "    ports:",
                  "      - \"3000:3000\"",
                  "    env_file:",
                  "      - .env",
                  "DOCKER_COMPOSE_EOF",
                  "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com",
                  "docker compose -f docker-compose.prod.yml pull api",
                  "docker compose -f docker-compose.prod.yml run --rm api bundle exec rails db:migrate",
                  "docker compose -f docker-compose.prod.yml up -d --remove-orphans api"
              ],
              "workingDirectory": ["/home/ec2-user/yubikirigennmann"]
          }
          EOF

              # Replace placeholders with actual values using different delimiter
              sed -i "s|\$DOT_ENV_PRODUCTION|${{ secrets.DOT_ENV_PRODUCTION }}|g" /tmp/ssm-params.json
              sed -i "s|\$AWS_ACCOUNT_ID|${{ secrets.AWS_ACCOUNT_ID }}|g" /tmp/ssm-params.json
              sed -i "s|\$AWS_REGION|${{ secrets.AWS_REGION }}|g" /tmp/ssm-params.json
              sed -i "s|\$ECR_API_REPOSITORY|${{ secrets.ECR_API_REPOSITORY }}|g" /tmp/ssm-params.json

              aws ssm send-command \
                --region ${{ secrets.AWS_REGION }} \
                --instance-ids "$instance_id" \
                --document-name "AWS-RunShellScript" \
                --parameters file:///tmp/ssm-params.json \
                --timeout-seconds 600 \
                --query "Command.CommandId" \
                --output text
            fi
          done