name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push API image to ECR
        id: build-api-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_API_REPOSITORY }}:$IMAGE_TAG -f ./backend/Dockerfile ./backend
          docker push $ECR_REGISTRY/${{ secrets.ECR_API_REPOSITORY }}:$IMAGE_TAG
          docker tag $ECR_REGISTRY/${{ secrets.ECR_API_REPOSITORY }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_API_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ secrets.ECR_API_REPOSITORY }}:latest

      - name: Build, tag, and push Nginx image to ECR
        id: build-nginx-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_NGINX_REPOSITORY }}:$IMAGE_TAG -f ./nginx/Dockerfile .
          docker push $ECR_REGISTRY/${{ secrets.ECR_NGINX_REPOSITORY }}:$IMAGE_TAG
          docker tag $ECR_REGISTRY/${{ secrets.ECR_NGINX_REPOSITORY }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_NGINX_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ secrets.ECR_NGINX_REPOSITORY }}:latest

      - name: Deploy to EC2 instances
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }},${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd yubikirigennmann
            
            echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env
            
            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export ECR_API_REPOSITORY=${{ secrets.ECR_API_REPOSITORY }}
            export ECR_NGINX_REPOSITORY=${{ secrets.ECR_NGINX_REPOSITORY }}
            
            cat << 'EOF' > docker-compose.prod.yml
            services:
              api:
                image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_API_REPOSITORY}:latest
                command: bundle exec puma -C config/puma.rb
                env_file:
                  - .env
              nginx:
                image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NGINX_REPOSITORY}:latest
                ports:
                  - "80:80"
                depends_on:
                  - api
                env_file:
                  - .env
            EOF
            
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            
            docker-compose -f docker-compose.prod.yml pull
            
            docker-compose -f docker-compose.prod.yml run --rm api bundle exec rails db:migrate
            
            docker-compose -f docker-compose.prod.yml up -d