name: CD - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2 via SSM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Deploy to EC2 instances
        run: |
          instance_ids=("${{ secrets.EC2_INSTANCE_ID_1 }}" "${{ secrets.EC2_INSTANCE_ID_2 }}")
          
          for instance_id in "${instance_ids[@]}"; do
            if [ -n "$instance_id" ]; then
              echo "Deploying to instance: $instance_id"

              aws ssm send-command \
                --region ${{ secrets.AWS_REGION }} \
                --instance-ids "$instance_id" \
                --document-name "AWS-RunShellScript" \
                --parameters file://<(cat <<EOF
          {
              "commands": [
                  "export DOT_ENV_PRODUCTION='${{ secrets.DOT_ENV_PRODUCTION }}'",
                  "export AWS_ACCOUNT_ID='${{ secrets.AWS_ACCOUNT_ID }}'",
                  "export AWS_REGION='${{ secrets.AWS_REGION }}'",
                  "export ECR_API_REPOSITORY='${{ secrets.ECR_API_REPOSITORY }}'",
                  "bash <(curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/scripts/deploy.sh)"
              ]
          }
          EOF
          ) \
                --timeout-seconds 600 \
                --query "Command.CommandId" \
                --output text
            fi
          done