- name: Deploy to EC2 instances
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }},${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd yubikirigennmann
            echo "${{ secrets.DOT_ENV_PRODUCTION }}" > .env
            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export ECR_API_REPOSITORY=${{ secrets.ECR_API_REPOSITORY }}
            export ECR_NGINX_REPOSITORY=${{ secrets.ECR_NGINX_REPOSITORY }}
            
            cat << 'EOF' > docker-compose.prod.yml
            services:
              api:
                image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_API_REPOSITORY}:latest
                command: bundle exec puma -C config/puma.rb
                env_file:
                  - .env
              nginx:
                image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NGINX_REPOSITORY}:latest
                ports:
                  - "80:80"
                depends_on:
                  - api
                env_file:
                  - .env
            EOF
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml run --rm api bundle exec rails db:migrate
            docker-compose -f docker-compose.prod.yml up -d